services:
  frontend:
    build: frontend
    ports:
      - "5173:5173"
  strapiDB:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: strapi
    volumes:
      - ./db-data:/var/lib/postgresql/data
  strapi:
    build: strapi
    depends_on:
      - strapiDB
    ports:
      - "1337:1337"
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: strapiDB
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      JWT_SECRET: b8gt5k98c
      ADMIN_JWT_SECRET: b8gt5k98c
      APP_KEYS: b8gt5k98c
      NODE_ENV: production
      API_TOKEN_SALT: b8gt5k98c
      PUBLIC_URL: https://strapi.cristina-coellen.com
      PROXY: true
    volumes:
      - ./strapi/config:/opt/app/config
      - ./strapi/src:/opt/app/src
      - ./strapi/package.json:/opt/package.json
      - ./strapi/yarn.lock:/opt/yarn.lock
      - ./strapi/public/uploads:/opt/app/public/uploads
