name: Frontend CD
run-name: Builds frontend image and pushes it to the registry
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build the frontend image
        working-directory: frontend
        run: docker build -t rg.fr-par.scw.cloud/cristina/frontend:latest .
      - name: Login to the registry
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login rg.fr-par.scw.cloud -u cristina --password-stdin
      - name: Push the frontend image
        run: docker push rg.fr-par.scw.cloud/cristina/frontend:latest