name: Frontend CD
run-name: Builds frontend image and pushes it to the registry
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4