name: Frontend CD
run-name: Automated frontend deployment
on:
  tag:
    - 'v*.*.*'
jobs:
  build:
    name: Build and deploy the frontend
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build the frontend image
        working-directory: frontend
        run: docker build -t rg.fr-par.scw.cloud/cristina/frontend:latest . --build-arg NODE_ENV=production --build-arg VITE_VERSION=${{ github.ref_name }}
      - name: Login to the registry
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login rg.fr-par.scw.cloud -u cristina --password-stdin
      - name: Push the frontend image
        run: docker push rg.fr-par.scw.cloud/cristina/frontend:latest
      - name: Pull the frontend image
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            docker pull rg.fr-par.scw.cloud/cristina/frontend:latest
            cd ~/cristina
            docker compose up -d