name: Update Linux
run-name: Runs apt update and upgrade

on: [push]
jobs:
  update:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Connect to VPS via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            sudo apt update
            sudo apt upgrade -y